config/routes.rb
Rails.application.routes.draw do
  resources :pokemons do
  member do
    get "vote"
  end
end

  resources :userpokes do
  member do
    get "vote"
  end
end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/userpoke.rb
class Userpoke < ActiveRecord::Base
  belongs_to :pokemon
  belongs_to :user
  acts_as_votable 
end

app/controllers/userpokes_controller.rb
class UserpokesController < ApplicationController
  before_action :set_userpoke, only: [:show, :edit, :update, :destroy, :vote]

  # GET /userpokes
  # GET /userpokes.json
  def index
    @userpokes = Userpoke.all
  end

  # GET /userpokes/1
  # GET /userpokes/1.json
  def show
  end

  # GET /userpokes/new
  def new
    @userpoke = Userpoke.new
  end

  # GET /userpokes/1/edit
  def edit
  end

  # POST /userpokes
  # POST /userpokes.json
  def create
    @userpoke = Userpoke.new(userpoke_params)

    respond_to do |format|
      if @userpoke.save
        format.html { redirect_to @userpoke, notice: 'Userpoke was successfully created.' }
        format.json { render :show, status: :created, location: @userpoke }
      else
        format.html { render :new }
        format.json { render json: @userpoke.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userpokes/1
  # PATCH/PUT /userpokes/1.json
  def update
    respond_to do |format|
      if @userpoke.update(userpoke_params)
        format.html { redirect_to @userpoke, notice: 'Userpoke was successfully updated.' }
        format.json { render :show, status: :ok, location: @userpoke }
      else
        format.html { render :edit }
        format.json { render json: @userpoke.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userpokes/1
  # DELETE /userpokes/1.json
  def destroy
    @userpoke.destroy
    respond_to do |format|
      format.html { redirect_to userpokes_url, notice: 'Userpoke was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @userpoke.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userpoke
      @userpoke = Userpoke.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userpoke_params
      params.require(:userpoke).permit(:pokemon_id, :user_id)
    end
end

app/helpers/userpokes_helper.rb
module UserpokesHelper
end

app/views/userpokes/_form.html.erb
<%= form_for @userpoke, :html => { :class => 'form-horizontal form-model' } do |f| %>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  userpokes_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/userpokes/edit.html.erb
<%- model_class = Userpoke -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Userpoke %></h1>
</div>
<%= render :partial => 'form' %>

app/views/userpokes/index.html.erb
<%- model_class = Userpoke -%>
<div class="page-header">
  <h1><%=t '.title', :default => Userpoke %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @userpokes.each do |userpoke| %>
      <tr>
        <td><%= userpoke.id %></td>
        <td><%=l userpoke.created_at, format: :long %></td>
        <td>
          <%= link_to userpoke_path(userpoke), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to userpoke_path(userpoke), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_userpoke_path,
            :class => 'btn btn-primary' %>

app/views/userpokes/new.html.erb
<%- model_class = Userpoke -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Userpoke %></h1>
</div>
<%= render :partial => 'form' %>

app/views/userpokes/show.html.erb
<%- model_class = Userpoke -%>
<div class="page-header">
  <h1><%=t '.title', :default => Userpoke %></h1>
</div>

<div class="fieldset">
  <dl>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              userpokes_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_userpoke_path(@userpoke), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              userpoke_path(@userpoke),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>